Clippy fixes
SergiusIW/collider-rs pull request #8
Opened 2019-01-13 22:43 UTC by ckaran

This commit used clippy to find and fix a bunch things.  See the commit messages for what got fixed.

2019-01-15 04:59 UTC, SergiusIW commented on src/core/events.rs
> +        if (self.time - other.time).abs() < std::f64::EPSILON {
Exact equality is expected in this if statement. It is for a comparison tiebreaker.

2019-01-15 05:06 UTC, SergiusIW requested changes
Concerning the "Fixed float_cmp error" commit. Exact equality is expected in all of these cases. These equality checks should not have a tolerance associated with them. I will not merge the "Fixed float_cmp error" commit, as it may introduce unexpected behaviour.

2019-01-15 13:55 UTC, ckaran commented
OK, do you want me to revert those changes and make a new pull request?

2019-01-16 05:26 UTC, SergiusIW commented
Yes please. The other clippy fixes were fine.

2019-01-16 15:51 UTC, ckaran commented
OK, I've made the changes.  I'm not sure how GitHub handles updates to a pull request; do I close this one and create a new pull request, or do I just leave this as-is and wait for you to merge the new changes in?

2019-01-17 03:22 UTC, SergiusIW commented
You can make the changes in this pull request. You should be able to just revert the float_cmp commit and push to the clippy_fixes branch on ckaran/collider-rs.

2019-01-17 13:56 UTC, ckaran commented
And I've learned something new today! :smile: I didn't know that this was how you fixed a pull request, nor did I know about the `git revert` command.  Thank you for both!  Please let me know if the fixes pass muster.

2019-01-18 03:51 UTC, merged